### ISSUE TITLE
Simple way to check installed pyxis version

### ISSUE THREAD

**Issue by estepona** [NVIDIA/pyxis#125]
Hi, I wonder if there's a simple way to check the installed pyxis version? There is no CLI nor a version file. When I try to find it, it doesn't give any clue.
```
sudo find /usr -type f -iname *pyxis*
/usr/local/lib/slurm/spank_pyxis.so
/usr/local/share/pyxis/pyxis.conf
```

**Comment by flx42** [comment]
If you installed through a package, you can check its version:
```console
$ dpkg -l | grep pyxis
ii  nvslurm-plugin-pyxis                          0.16.1-1                                    amd64        Slurm plugin for launching containerized tasks
```

You can also check the slurmd log, it will print the pyxis version when slurmd starts:
```
$ sudo cat /var/log/slurm/slurmd.node-1.log | grep pyxis
[2023-09-12T16:03:55.192] pyxis: version v0.16.1
```

**Comment by estepona** [comment]
Thank you @flx42! That is helpful.

**Comment by cponder** [comment]
Just for the record, there's no way to query the information from a SLURM command-line?
I can get some information on the MPI plugins using
```
+ srun --mpi list
MPI plugin types are...
	none
	pmi2
	pmix
	cray_shasta
specific pmix plugin versions available: pmix_v4
```

**Comment by flx42** [comment]
@cponder no there isn't a way right now.
