### ISSUE TITLE
Version 0.17.0 breaks passing variables from systemd

### ISSUE THREAD

**Issue by mathrock74** [NVIDIA/pyxis#134]
pyxis version 0.17.0 seems to break the solution described in https://github.com/NVIDIA/pyxis/wiki/Setup#slurmd-configuration
I didn't have a real problem yet, but I noticed that variables defined in systemd EnvironmentFile don't get passed on to container anymore
I guess this is related to https://github.com/NVIDIA/pyxis/commit/e2de43353bafcdcaad50076d218b3f5b6899a766

Is this intended behavior?

thank you

**Comment by flx42** [comment]
Yes it's intended, those environment variables are for slurmd/slurmstepd but not for the container. slurmstepd will take care of setting the relevant PMIx environment variables for the container.

As far as I know (and I tested on a multiple systems), PMIx still works fine with pyxis 0.17.0. Let me know if you see any issue.

**Comment by mathrock74** [comment]
ok, thank you
