### ISSUE TITLE
Is there a single container instance per allocated node?

### ISSUE THREAD

**Issue by ocaisa** [NVIDIA/pyxis#141]
It's not clear to me from the documentation if the plugin is running a single container instance per allocated node or not. I ask because we have a container that uses [CernVM-FS](https://cernvm.cern.ch/fs/) and typically requires options like:
```
export SINGULARITY_BIND="${TMPDIR}/var-run-cvmfs:/var/run/cvmfs,${TMPDIR}/var-lib-cvmfs:/var/lib/cvmfs"
```
When executing an MPI program with singularity in this context we have had to do some gymnastics in the past to ensure that we have unique binds per MPI process, as this is what CVMFS expects (and you have a single instance of CVMFS per MPI process when using containers). If it can be guaranteed that there is only a single container instance per allocated node, then MPI codes would not have such a complication.

**Comment by flx42** [comment]
Yes, by design all ranks on the same node will be running inside the same container: same root filesystem, same user / mount namespaces.

**Comment by ocaisa** [comment]
Great, thanks!

**Comment by fno2010** [comment]
> Yes, by design all ranks on the same node will be running inside the same container: same root filesystem, same user / mount namespaces.

@flx42 Can you explain why it is designed as this? In our setting, we need to replace some files in each running container. We put the file replacement at the beginning of a script. When we use `srun` to execute the script, each rank on the same node will run the script to replace the files inside the same container. Because of the race condition, the replacement may fail sometimes. Do you know how to avoid this?

**Comment by flx42** [comment]
For us it was the most common use case, and it avoids duplicating the container filesystem by default. The container filesystem is sometimes very big, ~25 GiB, and there are 8 ranks launched per node (one per GPU).

You can use a named container to prepare the changes with only one task per node before launching you application, something like that:
```console
$ srun --container-name=mycontainer --container-image=... -N8 --ntasks-per-node=1 touch /file
$ srun --container-name=mycontainer -N8 --ntasks-per-node=8 python app.py
```

**Comment by fno2010** [comment]
> For us it was the most common use case, and it avoids duplicating the container filesystem by default. The container filesystem is sometimes very big, ~25 GiB, and there are 8 ranks launched per node (one per GPU).
> 
> You can use a named container to prepare the changes with only one task per node before launching you application, something like that:
> 
> $ srun --container-name=mycontainer --container-image=... -N8 --ntasks-per-node=1 touch /file
> $ srun --container-name=mycontainer -N8 --ntasks-per-node=8 python app.py

Ah, I see. If the concern is about the storage, it makes sense. Thanks for the suggested solution :)
