### ISSUE TITLE
Can't pass environment variables to entrypoint

### ISSUE THREAD

**Issue by skandermoalla** [NVIDIA/pyxis#145]
Hello,

I have an entrypoint that reads environment variables at runtime like `docker run --env FOO=1 CMD` but it seems like Pyxis only sets environment variables set with `export FOO=1; srun ... --container-env=FOO CMD` after the entrypoint has run, so they're not yet available when the entrypoint is running.

Is this by design? How can one make the entrypoint read environment variables set at runtime?

Thanks

```bash
> enroot version
3.5.0
```

**Comment by flx42** [comment]
Looks like it's a bug, I will try to fix it when possible.

**Comment by flx42** [comment]
This should be fixed in the next release, note that only variables specified with `--container-env` will be passed to the entrypoint.
