### ISSUE TITLE
Unpacking on compute node

### ISSUE THREAD

**Issue by mmg10** [NVIDIA/pyxis#147]
I am using AWS ParallelCluster for SLURM and it has pyxis/enroot post-installation step. I run my batch script via `sbatch task.sh` whereas `task.sh` contains `--container-image ${PWD}/llm.sqsh` as the argument. Every time I submit a job to a single node, the `llm.sqsh` image (that has already been imported on a shared path via `enroot import -o llm.sqsh docker://...torch:llm` is unpacked. I know this because the disk usage increases each time, and then reduces before the task execution begins. Is it possible to re-use the the unpacked filesystem for different runs? 

Also, I intend to run a multi-node training job and want to share the unpacked container? Will this be possible?

**Comment by flx42** [comment]
you should use `--container-name` for this purpose.
