### ISSUE TITLE
--container-image behavior different between cmd line and batch file

### ISSUE THREAD

**Issue by RHudsonH** [NVIDIA/pyxis#148]
I'm trying to use an image from quay.io which requires a login to pull. I have create a .credentials file in ~/.config/enroot/. if I put the --container-image flag in my batch file:

`#SBATCH  --container-image=quay.io#repository/image:tag`

My job fails almost instantly and the error out shows that enroot tried to log in anonymously and got a 404.

However, if I remove the line from the batch file and put it on the command line:

`sbatch --container-image=quay.io#repository/image:tag batch_file.sh`

It works just fine picking up my credentials from the ~/.config/enroot/.credentials file.

**Comment by flx42** [comment]
Hello, please see the note in this section:
https://github.com/NVIDIA/pyxis#sbatch

**Comment by RHudsonH** [comment]
The sad thing is I knew that at some point and forgot about it. Thank you for the reply!
