### ISSUE TITLE
Fail to run due to seccomp_filter error

### ISSUE THREAD

**Issue by basvandervlies** [NVIDIA/pyxis#17]
I have installed this plugin on a Debian host stretch (9.12)  with slurm 19.05.5. . SECCOMP is enabled:  
```
oot# grep SECCOMP /boot/config-$(uname -r)
CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
CONFIG_SECCOMP_FILTER=y
CONFIG_SECCOMP=y
```

I have patched the source to print the error code and removed the exit/ So the error messages are printed and the container is still started:
```
bas@r33n4:~/enroot$ srun --container-name=testje --container-image=$HOME/enroot/ubuntu.sqsh --pty cat /etc/os-release
slurmstepd: task_p_pre_launch: Using sched_affinity for tasks
slurmstepd: error: pyxis: seccomp filter failed: Invalid argument:22
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by flx42** [comment]
@basvandervlies thanks for reporting!
Could you also try by replacing `SECCOMP_FILTER_FLAG_SPEC_ALLOW` with `0` here?
https://github.com/NVIDIA/pyxis/blob/07cf4f37877fb12932e0d3f72fac93a28df62f8c/seccomp_filter.h#L63

Thank you

**Comment by basvandervlies** [comment]
@flx42 Thanks that solves the problem.

**Comment by flx42** [comment]
Thanks for checking! I fixed it in https://github.com/NVIDIA/pyxis/commit/6bd15a0ba36e48c21bf22c494dec0ac8c6e895b6
