### ISSUE TITLE
ENROOT_ROOTFS_WRITABLE not honored

### ISSUE THREAD

**Issue by coolinger** [NVIDIA/pyxis#19]
The container launched by pyxis always has the container root filesystem mounted writable, even if ENROOT_ROOTFS_WRITABLE is set to "no" in /etc/enroot/enroot.conf.

It would be nice if there was an option to explicitly mount it rw, or use the defaults instead of the hardcoded "--rw" in [pyxis_slurmstepd.c](https://github.com/NVIDIA/pyxis/blob/6bd15a0ba36e48c21bf22c494dec0ac8c6e895b6/pyxis_slurmstepd.c#L1135-L1137)

Regards
Quirin

**Comment by flx42** [comment]
You are right, this was an oversight. I have now done the change.

**Comment by flx42** [comment]
Thanks for reporting!
