### ISSUE TITLE
pyxis: unable to use locally built and tagged images

### ISSUE THREAD

**Issue by sfeltman** [NVIDIA/pyxis#23]
Pyxis is prepending "docker://" to image names given to the --container-image argument. This doesn't allow for local images built and tagged before the call to srun. While ultimately the solution for me will be to use a registry, it would be nice to allow explicit use of "dockerd://imagetag" as an argument as enroot seems to.

Thanks

**Comment by flx42** [comment]
I don't think we're going to implement this directly in pyxis, sorry. Instead, you can use `enroot import` and pass the squashfs file to pyxis:
```console
$ enroot import dockerd://flx42/test 
$ srun --container-image ./test.sqsh 
```

We don't have the docker daemon on our clusters, and it doesn't really make sense for a cluster: across nodes, each docker daemon will have a different state. Unless you are planning to use `docker build` then use pyxis on a single node only?

**Comment by Averylamp** [comment]
Hi @flx42, I saw that the usage of `dockerd` with pyxis has come up in a couple issues.  I was curious if there were plans to support it?  Thanks!

**Comment by flx42** [comment]
Not for now, it's not really complicated to add but it's not a feature we would use in any of our clusters.

**Comment by Averylamp** [comment]
Would you accept a PR that adds it?

**Comment by flx42** [comment]
Not right now, but I will consider that for a later release, thanks!

**Comment by flx42** [comment]
Finally added support in https://github.com/NVIDIA/pyxis/commit/a72ec8d53b317674e0841c11a66d6eb6b6b814ac

**Comment by Averylamp** [comment]
> Finally added support in [a72ec8d](https://github.com/NVIDIA/pyxis/commit/a72ec8d53b317674e0841c11a66d6eb6b6b814ac)

Thank you!
