### ISSUE TITLE
Support for private registries?

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/pyxis#34]
Does pyxis support token protected private docker registries?

By reading https://github.com/NVIDIA/pyxis/issues/8#issuecomment-560544044 it would seem no.

**Comment by microbioticajon** [comment]
Interesting timing, I am researching if pyxis will work with private AWS ECR repositories via the Amazon ECR Docker Credential Helper. Further information regarding private repositories would be helpful.

**Comment by lukeyeager** [comment]
I'd start by reading this section of the enroot documentation:
https://github.com/NVIDIA/enroot/blob/v3.2.0/doc/cmd/import.md#description

**Comment by flx42** [comment]
It does work for multiple private repositories we have tested. Please test with enroot like @lukeyeager mentioned, and if it doesn't work let us know (by filing an issue against enroot if you see the problem with just enroot).

**Comment by 3XX0** [comment]
@microbioticajon we didn't test ECR but if I had to guess it's probably something like this:

`machine <ACCOUNT>.dkr.ecr.<REGION>.amazonaws.com login AWS password $(aws ecr get-login-password)`

**Comment by flx42** [comment]
Please reopen if you see a problem :)
