### ISSUE TITLE
Slurm plugin with rootless docker (instead)

### ISSUE THREAD

**Issue by elgalu** [NVIDIA/pyxis#38]
NVIDIA/deepops is [adding](https://github.com/NVIDIA/deepops/pull/824) support for [rootless docker](https://github.com/NVIDIA/deepops/blob/f36b3e7a3bd9/docs/container/docker-rootless.md)

Maybe it makes sense to think about a Slurm plugin that integrates with rootless docker instead of Enroot?

> Alternatives, such as Singularity and Enroot, also enable an unprivileged user to utilize containerization. The added convenience of rootless docker is that if one is working with docker containers it would be more straightforward to build and run docker containers instead of having to convert to another container format.

**Comment by flx42** [comment]
I'm sure it would be possible to create a similar Slurm plugin with a similar API than pyxis (i.e. `--container-{image,name,mounts}`). But there is no plan to work on this as far as I know, feel free to start working on it if you want :)


Rootless docker still provides too much isolation by default which will be a problem for HPC workloads, and it uses slirp4netns (even with `--net=host`) which will be detrimental to performance.

BTW, with pyxis you don't get the inconvenience of "of having to convert to another container format", this is taken care behind the scenes (while still having the option to use a squashfs image).

**Comment by flx42** [comment]
Closing since this is not really a pyxis issue (would be a new project, and as I said there is no plan right now to work on that).
