### ISSUE TITLE
Is there any way to tell pyxis where to create squashfs?

### ISSUE THREAD

**Issue by dchirikov** [NVIDIA/pyxis#41]
I am getting the following error
```
slurmstepd: error: pyxis:     Write failed because No space left on device
slurmstepd: error: pyxis:     FATAL ERROR:Failed to write to output filesystem
slurmstepd: error: pyxis:     Parallel mksquashfs: Using 2 processors
slurmstepd: error: pyxis:     Creating 4.0 filesystem on /run/pyxis/1000/7.0.squashfs, block size 131072.
```
My guess is that I am trying to pull the image more than 10G, while I have only 8G memory (this is a test cluster) and `/run` is `tmpfs` mounted to memory. Would be handy to instruct pyxis to put its data somewhere else where I have enough space.
Any tips for that?
Thank you in advance.

**Comment by flx42** [comment]
Hello @dchirikov 

Yes, there is a way, it's `runtime_path` in `pyxis.conf`:
https://github.com/NVIDIA/pyxis/wiki/Setup#slurm-plugstack-configuration

**Comment by dchirikov** [comment]
Thank you.
This worked flawlessly!
