### ISSUE TITLE
deb installation error

### ISSUE THREAD

**Issue by moonsooyoung** [NVIDIA/pyxis#49]
Hello,

I installed Slurm 20.11.4 with a deb package and successfully installed Pyxis following your instructions for 'make install' and failed with a deb package as below: 
$ make orig
$ make deb
...
dpkg-checkbuilddeps: error: Unmet build dependencies: libslurm-dev

Can you kindly share your insights what the error message actually means?
Does the deb installation of Pyxis require any specific Slurm build?

**Comment by flx42** [comment]
Hello

> Can you kindly share your insights what the error message actually means?
>  Does the deb installation of Pyxis require any specific Slurm build?

It means Slurm is expected to be installed as a deb package when trying to generate a pyxis deb package.

If you installed Slurm from sources, you can either stick with doing just `make install` or you can generate a deb package after removing `libslurm-deb` as a build time dependency from here:
https://github.com/NVIDIA/pyxis/blob/54dddd46280784879ce2178f36ce6e0c4afb9ee3/debian/control#L7

**Comment by moonsooyoung** [comment]
Hi Felix,

Thank you for the clarification. It works after replacing 'libslurm-dev' in the control file with the corresponding name of my package. :-)
