### ISSUE TITLE
how to use private registry?

### ISSUE THREAD

**Issue by mathrock74** [NVIDIA/pyxis#51]
I'm trying to use the private registry that is installed with deepops.
I'm running 

ENROOT_ALLOW_HTTP=yes srun --container-image='deepops-login2:5000#library/ubuntu' grep PRETTY /etc/os-release

which gives

pyxis: importing docker image ...
slurmstepd: error: pyxis: child 273922 failed with error code: 35
slurmstepd: error: pyxis: failed to import docker image
slurmstepd: error: pyxis: printing contents of log file ...
slurmstepd: error: pyxis:     [INFO] Querying registry for permission grant
slurmstepd: error: pyxis:     curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
slurmstepd: error: pyxis: couldn't start container
slurmstepd: error: pyxis: if the image has an unusual entrypoint, try using --no-container-entrypoint
slurmstepd: error: spank: required plugin spank_pyxis.so: task_init() failed with rc=-1
slurmstepd: error: Failed to invoke spank plugin stack
srun: error: deepops-node3: task 0: Exited with exit code 1

This looks like talking HTTPS to HTTP port to me. How can the deepops private registry be used with enroot/pyxis?

thx

PS
Using enroot/pyxis with other registries (nvcr.io) works.
Using deepops private registry with docker works.

**Comment by flx42** [comment]
Can you try setting ENROOT_ALLOW_HTTP=yes in your enroot.conf directly?

**Comment by mathrock74** [comment]
that works indeed, thanks a lot
