### ISSUE TITLE
Error while installing Pyxis

### ISSUE THREAD

**Issue by rahulakolkar** [NVIDIA/pyxis#56]
Hi Team,
We are working with the NVIDIA India team to install Pyxis on our cluster and we are experiencing the following errors -

1) An error before updating glibc-devel package-
_**cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic  -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -I/usr/include/slurm -I/usr/include/slurm-wlm  -MMD -MF common.d -c common.c 
common.c:5:20: fatal error: stdlib.h: No such file or directory 
 #include <stdlib.h> 
                    ^ 
compilation terminated. 
make: *** [common.o] Error 1**_
 
2) An error after updating the glibc-devel package-

**_cc -std=gnu11 -O2 -g -Wall -Wunused-variable -fstack-protector-strong -fpic  -D_GNU_SOURCE -D_FORTIFY_SOURCE=2 -I/usr/include/slurm -I/usr/include/slurm-wlm  -MMD -MF common.d -c common.c 
In file included from common.h:6:0, 
                 from common.c:8: 
/usr/include/sys/syscall.h:24:24: fatal error: asm/unistd.h: No such file or directory 
 #include <asm/unistd.h>_**

**System Summary:
OS Version: Centos-7.6
gcc version: gcc-4.8.5
Enroot version: 3.3.0
Slurm Version: 19.05.0
Pyxis version: 0.7.0**

**Comment by flx42** [comment]
Try installing the `kernel-headers` package.

But your system seems to be in a weird state, as `glibc-devel` and `kernel-headers` should come with the `gcc` package.
For instance, this is sufficient to build pyxis starting from the minimal CentOS 7 container image:
```
FROM centos:7

RUN yum install -y epel-release && \
    yum install -y gcc git slurm-devel make

RUN git clone -b v0.11.0 https://github.com/NVIDIA/pyxis.git /usr/local/src/pyxis && \
    cd /usr/local/src/pyxis && \
    make -j && make install
```

**Comment by shubhammehta03** [comment]
Dear Team,
"_gcc git slurm-devel make_" are already installed in the image, its just asking for an update.
As the system is in production, we cant update the dependencies.

After running the second command, following errors are shown:

 **pyxis_slurmstepd.c:5:26: fatal error: linux/limits.h: No such file or directory
 #include <linux/limits.h>
                            ^
  pyxis_dispatch.c:5:25: fatal error: slurm/spank.h: No such file or directory
 #include <slurm/spank.h>
                         ^
compilation terminated.
compilation terminated.
make: *** [pyxis_slurmstepd.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [pyxis_dispatch.o] Error 1
In file included from /usr/include/errno.h:35:0,
                 from pyxis_srun.c:5:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
 # include <linux/errno.h>
                          ^
In file included from /usr/include/errno.h:35:0,
                 from pyxis_slurmd.c:5:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
 # include <linux/errno.h>
                          ^
compilation terminated.
compilation terminated.
In file included from /usr/include/errno.h:35:0,
                 from enroot.c:7:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
 # include <linux/errno.h>
                          ^
compilation terminated.
config.c:7:25: fatal error: slurm/spank.h: No such file or directory
 #include <slurm/spank.h>
                         ^
compilation terminated.
make: *** [pyxis_srun.o] Error 1
make: *** [pyxis_slurmd.o] Error 1
In file included from args.c:9:0:
args.h:11:25: fatal error: slurm/spank.h: No such file or directory
 #include <slurm/spank.h>
                         ^
compilation terminated.
In file included from common.h:6:0,
                 from common.c:10:
/usr/include/sys/syscall.h:24:24: fatal error: asm/unistd.h: No such file or directory
 #include <asm/unistd.h>
                        ^
compilation terminated.
make: *** [enroot.o] Error 1
make: *** [config.o] Error 1
make: *** [args.o] Error 1
make: *** [common.o] Error 1**

**Comment by shubhammehta03** [comment]
Dear Team,
"gcc git slurm-devel make" are already installed in the image, its just asking for an update.
As the system is in production, we cant update the dependencies.

After running the second command, following errors are shown:

pyxis_slurmstepd.c:5:26: fatal error: linux/limits.h: No such file or directory
 #include <linux/limits.h>
                          ^
pyxis_dispatch.c:5:25: fatal error: slurm/spank.h: No such file or directory
 #include <slurm/spank.h>
                         ^
compilation terminated.
compilation terminated.
make: *** [pyxis_slurmstepd.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [pyxis_dispatch.o] Error 1
In file included from /usr/include/errno.h:35:0,
                 from pyxis_srun.c:5:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
 # include <linux/errno.h>
                          ^
In file included from /usr/include/errno.h:35:0,
                 from pyxis_slurmd.c:5:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
 # include <linux/errno.h>
                          ^
compilation terminated.
compilation terminated.
In file included from /usr/include/errno.h:35:0,
                 from enroot.c:7:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
 # include <linux/errno.h>
                          ^
compilation terminated.
config.c:7:25: fatal error: slurm/spank.h: No such file or directory
 #include <slurm/spank.h>
                         ^
compilation terminated.
make: *** [pyxis_srun.o] Error 1
make: *** [pyxis_slurmd.o] Error 1
In file included from args.c:9:0:
args.h:11:25: fatal error: slurm/spank.h: No such file or directory
 #include <slurm/spank.h>
                         ^
compilation terminated.
In file included from common.h:6:0,
                 from common.c:10:
/usr/include/sys/syscall.h:24:24: fatal error: asm/unistd.h: No such file or directory
 #include <asm/unistd.h>
                        ^
compilation terminated.
make: *** [enroot.o] Error 1
make: *** [config.o] Error 1
make: *** [args.o] Error 1
make: *** [common.o] Error 1

**Comment by shubhammehta03** [comment]
Dear Team,
" gcc git slurm-devel make " are already installed in the image. As system is in production mode, we cant update them.

Following errors are there when we run the second command:

pyxis_slurmstepd.c:5:26: fatal error: linux/limits.h: No such file or directory
 #include <linux/limits.h>
                          ^
pyxis_dispatch.c:5:25: fatal error: slurm/spank.h: No such file or directory
 #include <slurm/spank.h>
                         ^
compilation terminated.
compilation terminated.
make: *** [pyxis_slurmstepd.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [pyxis_dispatch.o] Error 1
In file included from /usr/include/errno.h:35:0,
                 from pyxis_srun.c:5:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
 `# include <linux/errno.h>`
                          ^
In file included from /usr/include/errno.h:35:0,
                 from pyxis_slurmd.c:5:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
 `#include `<linux/errno.h>`
                          ^
compilation terminated.
compilation terminated.
In file included from /usr/include/errno.h:35:0,
                 from enroot.c:7:
/usr/include/bits/errno.h:24:26: fatal error: linux/errno.h: No such file or directory
` # include <linux/errno.h>`
                          ^
compilation terminated.
config.c:7:25: fatal error: slurm/spank.h: No such file or directory
 `#include <slurm/spank.h>`
                         ^
compilation terminated.
make: *** [pyxis_srun.o] Error 1
make: *** [pyxis_slurmd.o] Error 1
In file included from args.c:9:0:
args.h:11:25: fatal error: slurm/spank.h: No such file or directory
 `#include <slurm/spank.h>`
                         ^
compilation terminated.
In file included from common.h:6:0,
                 from common.c:10:
/usr/include/sys/syscall.h:24:24: fatal error: asm/unistd.h: No such file or directory
 #include <asm/unistd.h>
                        ^
compilation terminated.
make: *** [enroot.o] Error 1
make: *** [config.o] Error 1
make: *** [args.o] Error 1
make: *** [common.o] Error 1

**Comment by flx42** [comment]
This was a very mysterious issue, closing.
