### ISSUE TITLE
How to install pyxis if my slurm is installed from source?

### ISSUE THREAD

**Issue by LSC527** [NVIDIA/pyxis#57]
I installed slurm 20.11.8 according to the [official installation guide](https://slurm.schedmd.com/quickstart_admin.html). However, there is no directory that looks like /etc/slurm-llnl/plugstack.conf.d, which is needed in https://github.com/NVIDIA/pyxis#with-make-install

**Comment by flx42** [comment]
What about `/etc/slurm/`, does it exists? Where is your `slurm.conf` file
stored?

**Comment by LSC527** [comment]
Hi, I manually create `plugstack.conf` and `plugstack.conf.d` where I stored my `slurm.conf`. 
Then I run `srun --help | grep container-image` as described in https://github.com/NVIDIA/pyxis/wiki/Installation#verifying-srun
And it worked.
Thanks!

**Comment by LSC527** [comment]
I then run a simple srun cmd but got errors.
`srun --container-image="mlperf-nvidia:minigo" --container-name="minigo" ture`
pyxis: importing docker image ...
slurmstepd: error: pyxis: child 45353 failed with error code: 1
slurmstepd: error: pyxis: failed to import docker image
slurmstepd: error: pyxis: printing contents of log file ...
slurmstepd: error: pyxis:     [ERROR] Command not found: zstd
slurmstepd: error: pyxis: couldn't start container
slurmstepd: error: pyxis: if the image has an unusual entrypoint, try using --no-container-entrypoint
slurmstepd: error: spank: required plugin spank_pyxis.so: task_init() failed with rc=-1
slurmstepd: error: Failed to invoke spank plugin stack

Any ideas what's going on? thanks.
