### ISSUE TITLE
RFE: tag deb builds with the slurm version

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/pyxis#59]
In Slurm 21.08, spank plugin builds will only work for one major version of Slurm (https://github.com/SchedMD/slurm/commit/4fd2c08f8bdf3864e80b860b1394c3d58529a971). Can you make it so that `make deb` generates a deb package tagged with the proper version?

Some commands which might be helpful, depending on how you want to do it:
```console
$ # Not sure which version makes more sense here ...
$ readelf -d /lib/x86_64-linux-gnu/libslurm.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libslurm.so.37]
$ dpkg-query --show --showformat='${Version}\n' libslurm-dev
21.08.0.0~rc2+nvidia-1

$ # Might as well tag with the ubuntu version too while we're at it?
$ debchange --local 'slurm2108.' 'Build for Slurm 21.08'
$ debchange --release --distribution "$(lsb_release --codename --short)" ''
$ head -n1 debian/changelog
nvslurm-plugin-pyxis (0.11.0-1slurm2108.1) focal; urgency=medium
```

**Comment by flx42** [comment]
We decided we will take care of that in another way during our internal builds
