### ISSUE TITLE
Unable to start container image from local registry using sbatch command

### ISSUE THREAD

**Issue by gavillom** [NVIDIA/pyxis#68]
Good afternoon,

I've tried to compile current master branch rpm because I would be interested by --container-image option using sbatch command.

It feels like the syntaxe available with srun ([USER@][REGISTRY#]IMAGE[:TAG]|PATH) is not working using sbatch. I need to run container images from local registry.

```
$ cat run.slurm 
#!/bin/bash

#SBATCH --container-image=my-registry:5443#ubuntu

srun cat /etc/lsb-release

$ sbatch run.slurm 
Submitted batch job 483140

$ cat slurm-483140.out
pyxis: importing docker image: my-registry:5443
slurmstepd: error: pyxis: child 95267 failed with error code: 6
slurmstepd: error: pyxis: failed to import docker image
slurmstepd: error: pyxis: printing enroot log file:
slurmstepd: error: pyxis:     [INFO] Querying registry for permission grant
slurmstepd: error: pyxis:     curl: (6) Could not resolve host: registry-1.docker.io
```

I was very surprised by `pyxis: importing docker image: my-registry:5443` and `Could not resolve host: registry-1.docker.io` that shows image tries to be got from official Docker registry.

Is it planned to support the same syntaxe as srun command ?

Thanks

Best regards,

**Comment by flx42** [comment]
Hello,

I think Slurm interpret this as a comment within a comment:
```console
#SBATCH --container-image=my-registry:5443#ubuntu
```
So it is stripping the suffix `#ubuntu` and passing just `my-registry:5443` to pyxis. 

Can you try escaping the `#`?
```console
#SBATCH --container-image=my-registry:5443\#ubuntu
```

Or pass the image from the sbatch command line:
```console
$ sbatch --container-image my-registry:5443#ubuntu run.sub
```

**Comment by flx42** [comment]
Done, thanks for reporting this!
