### ISSUE TITLE
ParallelCluster

### ISSUE THREAD

**Issue by maziarraissi** [NVIDIA/pyxis#69]
How can I install pyxis on a cluster created by parallelcluster 3.0?

ParallelCluster installs slurm on /opt/slurm. So I added "CPPFLAGS = -I/opt/slurm/include" and "LDFLAGS = -L/opt/slurm/lib" to the pyxis Makefile. In the Makefile, I also modified "prefix ?= /user/local" to "prefix ?= /opt/slurm". Now, the command "sudo make install" seems to work. I also created a folder called "/etc/slurm-llnl/plugstack.conf.d" and then ran the following modified command: "sudo ln -s /opt/slurm/share/pyxis/pyxis.conf /etc/slurm-llnl/plugstack.conf.d/pyxis.conf". I also copied the file "/etc/chef/cookbooks/aws-parallelcluster/files/default/slurmd.service" to "/etc/systemd/system". This will let us run the following command without errors: "sudo systemctl restart slurmd"

However, when I type "srun --help | grep container" nothing shows. This means that the pyxis plugin is not installed.

What am I doing wrong?

**Comment by flx42** [comment]
Please try the `strace` approach mentioned here: https://github.com/NVIDIA/pyxis/wiki/Installation#verifying-srun

It should show you which plugin files are being resolved by `srun`, and it might show why your `pyxis.conf` file isn't processed.

**Comment by maziarraissi** [comment]
Thanks for your reply. In the following, please find the output of strace.

strace -e openat srun --help >/dev/null 

openat(AT_FDCWD, "/opt/slurm/lib/slurm/tls/haswell/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/slurm/lib/slurm/tls/haswell/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/slurm/lib/slurm/tls/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/slurm/lib/slurm/tls/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/slurm/lib/slurm/haswell/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/slurm/lib/slurm/haswell/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/slurm/lib/slurm/x86_64/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/opt/slurm/lib/slurm/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/libslurmfull.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/etc/slurm.conf", O_RDONLY) = 3
openat(AT_FDCWD, "/opt/slurm/etc/slurm_parallelcluster.conf", O_RDONLY) = 4
openat(AT_FDCWD, "/opt/slurm/etc/pcluster/slurm_parallelcluster_myslurmqueue_partition.conf", O_RDONLY) = 5
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libnss_compat.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libnss_nis.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libnsl.so.1", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/passwd", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/select_cray_aries.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/select_linear.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/select_cons_tres.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/select_cons_res.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/switch_none.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/lib/slurm/switch_cray_aries.so", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/slurm/etc/plugstack.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
+++ exited with 0 +++

**Comment by flx42** [comment]
```
openat(AT_FDCWD, "/opt/slurm/etc/plugstack.conf", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
So you don't have the default `plugstack.conf` file as described in: https://slurm.schedmd.com/spank.html#SECTION_CONFIGURATION
Try creating this file at `/opt/slurm/etc/plugstack.conf` with an `include` directive that will allow Slurm to find your `pyxis.conf` file (no need to symlink the `pyxis.conf` file as long as it can be found from `plugstack.conf`).

**Comment by flx42** [comment]
@maziarraissi did you fix your problem?

**Comment by maziarraissi** [comment]
@flx42 you were really helpful, but I ran into some other issues with enroot and gave up. You can close the issue. Thanks!
