### ISSUE TITLE
enroot import container_image

### ISSUE THREAD

**Issue by cheyunfei** [NVIDIA/pyxis#70]
Hello, I'm trying run a container image by slurm. And I have installed pyxis and enroot.

But when the program start , there is an error happend.
"URL https://registry-1.docker.io/v2/library/mlperf-nvidia/manifests/minigo returned error code: 401 Unauthorized"

Finally, I figure out that when Pyxis calls the "enroot" command, Pyxis will use "enroot import docker://image[:TAG]" by default. It will pull container image from a remote registry and I haven't a account for this website, "https://registry-1.docker.io/v2".

Now, I want Pyxis to call "enroot import dockerd://image[:TAG]" instead of "enroot import docker://image[:TAG]". Then, I can use container image from the Docker daemon instead of from a remote registry.

So, how can I do ? Thanks.

**Comment by cheyunfei** [comment]
Or, how can I config some environment variables ?

**Comment by cheyunfei** [comment]
My command is : 
**srun --container-image="mlperf-nvidia:minigo" --container-name="minigo"**

when I use:
**srun --container-image="dockerd://mlperf-nvidia:minigo" --container-name="minigo"**

I get a error:
**error: pyxis:     [ERROR] Invalid image reference: docker://dockerd://mlperf-nvidia:minigo**

**Comment by flx42** [comment]
Sorry, but you can't use the `dockerd://` import feature from enroot when using pyxis. Slurm clusters usually don't have the docker daemon running.

You can do something like this instead:
```console
$ enroot import dockerd://image:tag
$ srun --container-image ./image+tag.sqsh [...]
```

**Comment by cheyunfei** [comment]
> Sorry, but you can't use the `dockerd://` import feature from enroot when using pyxis. Slurm clusters usually don't have the docker daemon running.
> 
> You can do something like this instead:
> 
> ```
> $ enroot import dockerd://image:tag
> $ srun --container-image ./image+tag.sqsh [...]
> ```

Thanks , this problem have been solved. I have get a squashfs file by "enroot import dockerd://image:tag"
