### ISSUE TITLE
ERROR while pulling images

### ISSUE THREAD

**Issue by SolenoidWGT** [NVIDIA/pyxis#71]
Hi，everyone
I encountered some problems when running the pyxis test. It reported an error when I pulled the pytorch 20.02 image. The reason for the error was "curl: (22) The requested URL returned error: 401 Unauthorized". However I can see that “Authentication succeeded”. Why does this problem occur, am I missing some configuration?

Here is the error log:

✗ nvcr.io PyTorch 20.02
   (from function `run_srun' in file tests/./common.bash, line 32,
    in test file tests/docker_image.bats, line 22)
     `run_srun --container-image=nvcr.io#nvidia/pytorch:20.02-py3 sh -c 'echo $PYTORCH_VERSION'' failed
   + srun -N1 --oversubscribe --container-image=nvcr.io#nvidia/pytorch:20.02-py3 sh -c echo $PYTORCH_VERSION
   pyxis: importing docker image: nvcr.io#nvidia/pytorch:20.02-py3
   slurmstepd: error: pyxis: child 129103 failed with error code: 1
   slurmstepd: error: pyxis: failed to import docker image
   slurmstepd: error: pyxis: printing enroot log file:
   slurmstepd: error: pyxis:     [INFO] Querying registry for permission grant
   slurmstepd: error: pyxis:     [INFO] Authenticating with user: <anonymous>
   slurmstepd: error: pyxis:     [INFO] Authentication succeeded
   slurmstepd: error: pyxis:     [INFO] Fetching image manifest list
   slurmstepd: error: pyxis:     [INFO] Fetching image manifest
   slurmstepd: error: pyxis:     [INFO] Downloading 59 missing layers...
   slurmstepd: error: pyxis:     curl: (22) The requested URL returned error: 401 Unauthorized
   slurmstepd: error: pyxis: couldn't start container
   slurmstepd: error: pyxis: if the image has an unusual entrypoint, try using --no-container-entrypoint
   slurmstepd: error: spank: required plugin spank_pyxis.so: task_init() failed with rc=-1
   slurmstepd: error: Failed to invoke spank plugin stack
   srun: error: XXXXXXX: task 0: Exited with exit code 1
   + exit status: 1
  
Here is my system info:
centos 7
enroot 3.4.0
slurm 20.11.8-6 
pyxis 0.12.0
Docker 20.10.12

Thank you all

**Comment by flx42** [comment]
Hello,

It might have been a temporary issue with the NVIDIA container registry at `nvcr.io`, is it still happening with 100% frequency?

You could also check if you have more luck with the very latest pytorch image:
```
$ enroot import docker://nvcr.io#nvidia/pytorch:22.01-py3
```

**Comment by SolenoidWGT** [comment]
> Hello,
> 
> It might have been a temporary issue with the NVIDIA container registry at `nvcr.io`, is it still happening with 100% frequency?
> 
> You could also check if you have more luck with the very latest pytorch image:
> 
> ```
> $ enroot import docker://nvcr.io#nvidia/pytorch:22.01-py3
> ```

Thank you very much, the problem should be related to the network configuration on my system, I will deal with it later. 
And I can use enroot to download the container mirror directly, and then use the absolute path to point out the container mirror location in pyxis.
