### ISSUE TITLE
Will containers launched by pyxis inherit the cgroup limitation in slurm?

### ISSUE THREAD

**Issue by SolenoidWGT** [NVIDIA/pyxis#72]
Will the containers started by pyxis be limited by slurm's cgroup.conf file, such as memory or cpu? I'm very curious about this, thank you all for your answers.

**Comment by 3XX0** [comment]
Yes, GPUs (gres/tres) as well.

**Comment by SolenoidWGT** [comment]
> Yes, GPUs (gres/tres) as well.

That's cool. Thank you very much!   : )
