### ISSUE TITLE
`nvslurm-plugin-pyxis` packages do not readily work with hardened enroot

### ISSUE THREAD

**Issue by AlexTMjugador** [NVIDIA/pyxis#74]
When building the Pyxis plugin Debian package with `make deb`, the generated package depends on the `enroot` package. This means that to use the hardened variant of enroot, distributed in the `enroot-hardened` package, it is necessary to either modify the `debian/control` file or force install broken packages.

After hacking the `debian/control` file to add a requirement to `enroot-hardened` instead of `enroot`, a quick test showed that the Pyxis plugin v0.7.0 worked fine with this hardened variant, as expected. So as far as I can see there is no reason to limit the dependency to the non-hardened variant.

As an user, I think it'd be better if `nvslurm-plugin-pyxis` depended on a metapackage provided by `enroot` or `enroot-hardened`, or at least its dependencies were satisfied by one of those packages.

I've not tested RPM packages, but their `pyxis.spec` file indicates that they also have this problem.

**Comment by flx42** [comment]
Good catch, thank you!

**Comment by kcgthb** [comment]
Hi @flx42 !

As you mentioned in https://github.com/NVIDIA/pyxis/issues/77#issuecomment-1119818498, the `or` syntax is not supported the the stock `rpm` version in RHEL/CentOS 7.x (that capability [has been added](https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html) in RPM 4.13, and el7 distros ship RPM 4.11.3).

One workaround could be to depend on one of the files that `enroot` and `enroot-hardened` both provide, like `/usr/bin/enroot`.
But then we would loose the possibility to require a minimum version (like >= 3.10). So maybe not ideal either.

I guess the right way to do this would be for the `enroot` package to provide a common namespace for both the `enroot` and `enroot-hardened` flavors, that `pyxis` could depend on.

**Comment by flx42** [comment]
@kcgthb can you please test with the latest commit on branch `master`?
Thanks

**Comment by kcgthb** [comment]
@flx42 that's a good compromise, I think. 
Thanks!
