### ISSUE TITLE
srun exits while container export is still running

### ISSUE THREAD

**Issue by jfolz** [NVIDIA/pyxis#76]
Some of our users alerted us that they could not launch their images saved with `--container-save`. We found this was because they were too fast. `srun` had exited, suggesting to them that the saved image was now usable, yet the export process was still running on the compute node. This seems odd, since [the code](https://github.com/NVIDIA/pyxis/blob/c469c03dca7b799243499132ce8a5cfecc009211/pyxis_slurmstepd.c#L1209) suggests that it should wait until the export finishes.

We're running Slurm 20.02.7, Pyxis 0.12.0, and Enroot 3.1.0.
I can't say for certain if it was working with earlier versions of Pyxis, or if by coincidence the export always finished before attempting to use the image, but we were only recently made aware of this.

**Comment by flx42** [comment]
Thanks for the bug report. I can reproduce the issue by injecting an artificial delay before saving the container image. So looks like there slurmstepd for step N is indeed executing concurrently with job N+1. This might require a slightly different approach in the code.

**Comment by flx42** [comment]
Hopefully this is fixed in 0.13. Let me know if you get a change to deploy the new version and confirm it is fixed.

**Comment by jfolz** [comment]
That was fast 😄 will do.

**Comment by jfolz** [comment]
Can confirm it now works as intended 👍 thanks again for the quick turnaround 😄
