### ISSUE TITLE
RPM can no longer be build on RH/CentOS 7

### ISSUE THREAD

**Issue by martialblog** [NVIDIA/pyxis#77]
Hi,

I think due to this change https://github.com/NVIDIA/pyxis/commit/bde76151d75450f9be3cbc00acd954af64e0215d the RPM can no longer be build on RH/CentOS 7

```
ORTIFY_SOURCE=2 -DPYXIS_VERSION=\"0.13.0\"  -MMD -MF enroot.d -c enroot.c
pyxis_slurmstepd.c:18:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
```

The latest `gcc` version appears to be 4.8.5 on these systems

```
podman run -ti --rm docker.io/centos:7
[root@0736c2bfdab9 /]# yum install -y gcc
[root@0736c2bfdab9 /]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```

Or am I doing anything wrong? I'm not saying it should still be supported, but a little hint in the release notes or the README would help.

Cheers
Markus

**Comment by flx42** [comment]
Sorry about that, it should be fixed now.

Looks like https://github.com/NVIDIA/pyxis/commit/aaabef002d43d8423f967db78d2c8d34cdcfe913 can also cause problem on older versions of rpm. Not sure if there is a good way to fix this, but that's easy to workaround manually with a little `sed`.

**Comment by martialblog** [comment]
@flx42 Awesome. Thanks. 

Small follow up, any chance we can get some pre-built rpm/debs on the release page?

Cheers

**Comment by flx42** [comment]
> Small follow up, any chance we can get some pre-built rpm/debs on the release page?

Sorry, but that's not planned right now.
