### ISSUE TITLE
Cannot run nccl tests inside a container

### ISSUE THREAD

**Issue by rvencu** [NVIDIA/pyxis#81]
Using enroot/pyxis with parallelcluster and slurm and apparently something is wrong re initializing cuda for the host or container cause I get that

```
srun --mpi=pmix --partition=compute-od-gpu --gpus=8 --cpus-per-gpu=4 --container-image=shivanshupurohit/gpt-neox:76 /opt/nccl-tests/build/all_reduce_perf -b 1M -e 4G -f 2 -g 1
pyxis: importing docker image: shivanshupurohit/gpt-neox:76
pyxis: imported docker image: shivanshupurohit/gpt-neox:76
[compute-od-gpu-dy-p4d-24xlarge-1:08575] PMIX ERROR: ERROR in file gds_ds12_lock_pthread.c at line 168
# nThread 1 nGpus 1 minBytes 1048576 maxBytes 4294967296 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
#
# Using devices
compute-od-gpu-dy-p4d-24xlarge-1: Test CUDA failure common.cu:1045 'unknown error'
 .. compute-od-gpu-dy-p4d-24xlarge-1 pid 8575: Test failure common.cu:1007
srun: error: compute-od-gpu-dy-p4d-24xlarge-1: task 0: Exited with exit code 2
```

Happened the same when I tested a container in Singularity. I overcame that by creating a cuda context first in the host:
```
srun --partition=compute-od-gpu --nodes=1 --gpus=8 --cpus-per-gpu=4 --time=04:00:00 --pty bash -i
sudo modprobe nvidia_uvm && docker run --gpus=all public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3 nvidia-smi
singularity shell --nv docker://public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3
all_reduce_perf -b 1M -e 512M -f 2 -g 1
```

But I supposed enroot would not bring up such problems. Is there something I am missing at the host configuration?

**Comment by flx42** [comment]
Having to initialize CUDA on the host first usually means you haven't loaded the `nvidia_uvm` kernel module, you can verify if that's the case by using `lsmod | grep nvidia` when the NCCL application is failing.

This module can't be loaded from inside a container, see https://github.com/NVIDIA/nvidia-container-runtime/issues/85#issuecomment-546536764 for an explanation and ways to solve this.

**Comment by rvencu** [comment]
Udev rules were great and we ended up using them in the host

However did not had time to proceed and continue to test in the container. This task is still pending. Our users are employing the host OS for now to run their workloads

**Comment by flx42** [comment]
You might need to create the device file too, as shown in https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications

**Comment by lipovsek-aws** [comment]
hi, @flx42 is this possible that this issue is caused by preinstalled docker and nvidia-container-toolkit? Script that @rvencu posted (thanks Richard!) seems to be required to use our [DLAMI](https://docs.aws.amazon.com/dlami/latest/devguide/what-is-dlami.html). Any chance we could add this to nvidia hook? We're building bootstrap scripts to add pyxis support to AWS ParallelCluster (https://github.com/aws-samples/aws-parallelcluster-post-install-scripts/tree/pyxis/pyxis).

**Comment by flx42** [comment]
@lipovsek-aws are you asking if having `docker` or `nvidia-container-toolkit` installed would prevent `enroot` from working? No, I don't see how that would be the case.

Note that the script above from Richard is the one documented in the CUDA installation guide I linked above: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications

> Any chance we could add this to nvidia hook?

That wouldn't help under pyxis as it's run without `root`. But if you can run privileged there is already the feature `--load-kmods` in `nvidia-container-cli`. So running `sudo nvidia-container-cli --load-kmods info` should also work and should be similar to the bash script from the CUDA documentation.

> We're building bootstrap scripts to add pyxis support to AWS ParallelCluster (https://github.com/aws-samples/aws-parallelcluster-post-install-scripts/tree/pyxis/pyxis).

That's cool, don't hesitate to file more bugs if you need help :)
