### ISSUE TITLE
The sshd service can not work correctly in the container

### ISSUE THREAD

**Issue by kuangllbnu** [NVIDIA/pyxis#85]
BG: I just want to use ssh in containers.  I could successfully start the sshd in docker containers and login from other terminals. But failed when I use Slurm with pyxis to start the container. 

Here is an screenshot. 
![image](https://user-images.githubusercontent.com/28888701/182269661-912fdf43-0e21-4309-903f-3923a149c079.png)

If I start the sshd in the container with port 2222, when I try to login with ssh -p 2222, "Connection closed" was reported (Attached screen). 
If I kill the sshd, then try to login with ssh -p 2222, certainly "Connection refused" was shown.

**Comment by flx42** [comment]
My understanding is that sshd  by default verifies it can actually drop privileges:
https://github.com/openssh/openssh-portable/blob/141535b904b6fba01724444f38193a8599201f82/uidswap.c

So I don't think enroot can work with this use case given what it does to intercept setuid/setgid calls with seccomp, so you need to use `--no-container-remap-root` to run sshd as non-root.

**Comment by 3XX0** [comment]
Yes, see also https://github.com/NVIDIA/enroot/issues/92#issuecomment-922088508

**Comment by kuangllbnu** [comment]
> My understanding is that sshd by default verifies it can actually drop privileges: https://github.com/openssh/openssh-portable/blob/141535b904b6fba01724444f38193a8599201f82/uidswap.c
> 
> So I don't think enroot can work with this use case given what it does to intercept setuid/setgid calls with seccomp, so you need to use `--no-container-remap-root` to run sshd as non-root.

It could not work either, when I delete the option `--no-container-remap-root`
![image](https://user-images.githubusercontent.com/28888701/182279933-fec623c5-e342-40e3-ab60-a6cd63e51bbe.png)

**Comment by flx42** [comment]
You need to **add** `--no-container-remap-root`
