### ISSUE TITLE
document how to use enroot `.credentials` 

### ISSUE THREAD

**Issue by ltalirz** [NVIDIA/pyxis#89]
enroot offers the option to [deposit credentials for a container registry in a `.credentials` file](https://github.com/NVIDIA/enroot/blob/master/doc/cmd/import.md#description), which needs to be placed in the `ENROOT_CONFIG_PATH` directory.

I have prepared such a file and am able to successfully `enroot import docker://registry#image` from this registry.

However, when using `srun --container-image registry#image` it appears the `.credentials` file is ignored (e.g. `[INFO] Authenticating with user` does not pick up the correct username from the `.credentials` file).
I've tried explicitly `--export`ing the `ENROOT_CONFIG_PATH` variable via `srun`, but this did not fix the problem.

What is the recommended way for authenticating with a private registry with the pyxis plugin?

**Comment by flx42** [comment]
This should work fine, is it picking the right file for the credentials?

**Comment by ltalirz** [comment]
I can no longer reproduce this issue.
When using `export ENROOT_CONFIG_PATH=...` before using `srun`, pyxis 0.12 (with enroot 0.4.1) is able to authenticate with the container registry.
