### ISSUE TITLE
ENROOT_DATA_PATH ignored

### ISSUE THREAD

**Issue by matyro** [NVIDIA/pyxis#91]
Hi,
we are currently trying to deploy slurm with pyxis and enroot but experiencing problems with configuring the data path.

Currently /etc/enroot/enroot.conf is setup on the control host and all machines with the following paths:

```
ENROOT_RUNTIME_PATH /run/enroot/user-$(id -u)
ENROOT_CACHE_PATH /raid/enroot-cache/group-$(id -g)
ENROOT_DATA_PATH /raid/enroot-data/user-$(id -u)
```

But submitting a container via
`srun --container-image=nvcr.io/nvidia/tensorflow:22.08-tf2-py3 /bin/bash`

from a user account leads to the following error because home quota is exceeded:
` FATAL ERROR:write_file: failed to create file /home/XXX/.local/share/enroot/`

This suggested to me that the paths set in the config are overwritten somewhere.

Do you have an Idea?

**Comment by flx42** [comment]
Which version of pyxis are you using?

Is it happening for all users on every node? Or just some users or nodes?

**Comment by matyro** [comment]
Hi,
we are currently in the testing phase, so only a single test user (besides root) on two nodes. 

Pyxis (0.13.0) and enroot(3.4.0) are the newest tagged version.

**Comment by flx42** [comment]
I would try the following:

- Verify that `/etc/enroot/enroot.conf` is the same on all machines (you said it is, but double checking wouldn't hurt)
- Verify that you don't have a machine where enroot is installed twice: from sources (as `/usr/local/bin/enroot`) and from packages (as `/usr/bin/enroot`). If enroot installed from sources is used, it would be using a different `enroot.conf` file: `/usr/local/etc/enroot/enroot.conf`
- Check if importing the image with `enroot` works fine: `enroot import docker://nvcr.io/nvidia/tensorflow:22.08-tf2-py3`

**Comment by matyro** [comment]
Hi,
- enroot.conf is the same on all nodes
- this seems to be the problem, I build from source and therefore the config is located in /usr/local/bin/enroot and not in /etc/enroot where it was placed by our scripts. No packaged version could be found on any machine, therefore we simply used the wrong config directory. Is it possible to change it during compilation to /etc/enroot ?

Cheers
Dominik

**Comment by flx42** [comment]
You can override those variables:
https://github.com/NVIDIA/enroot/blob/9c6e979059699e93cfc1cce0967b78e54ad0e263/Makefile#L1-L7

e.g. to install like the deb packages, you would use the following:
```console
$ make prefix= exec_prefix=/usr datarootdir=/usr/share
```

**Comment by matyro** [comment]
Thank you very much for solving this "problem" we were facing. 
Now, something new is coming up during container creation:

```
nvidia-container-cli: mount error: file creation failed: /raid/enroot-data/user-9011/pyxis_59.0/run/nvidia-persistenced/socket: no such device or address
[ERROR] /raid/enroot//hooks.d/98-nvidia.sh exited with return code 1
```

**Comment by flx42** [comment]
Can you open an issue https://github.com/nvidia/libnvidia-container?

**Comment by matyro** [comment]
Sure
