### ISSUE TITLE
numactl error enroot/pyxis running nvidia hpc-benchmark

### ISSUE THREAD

**Issue by xinyx62** [NVIDIA/pyxis#94]
Hi team.
I have problem with run  nvidia hpc-benchmark  use pixys/enroot
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

I install all nodes:

slurm-19.05.5 (with pmix plugin)

nvslurm-plugin-pyxis-0.7.0-1
enroot-3.4.0
end, i use local image nvcr.io/nvidia/tensorflow:21.11-tf1-py3 , and use enroot import it into hpl+test.sqsh file.  

nvidia-smi topo -m 
![image](https://user-images.githubusercontent.com/35787534/197657500-6dbe30be-10d2-44a8-b3aa-8907aa9429cf.png)

This is my cmd:
srun -N 1 --ntasks-per-node=8 --cpu-bind=none --container-image ./hpl+test.sqsh  hpl.sh  --config dgx-a100 --da                 t /workspace/hpl-ai-linux-x86_64/sample-dat/HPL-dgx-a100-1N.dat

I got the error:
![image](https://user-images.githubusercontent.com/35787534/197658452-60b3fc2b-5a0a-4ad1-a4e7-21f53784e9fd.png)

and this also error:srun -N 1 --ntasks-per-node=8 --cpu-bind=none --container-image ./hpl+test.sqsh  /workspace/hpl.sh --cpu-affinity 0-10:0-10:0-10:0-10:0-10:0-10:0-10:0-10 --mem-affinity 0:0:0:0:0:0:0:0 --config dgx-a100 --dat /workspace/hpl-ai-linux-x86_64/sample-dat/HPL-dgx-a100-1N.dat
![image](https://user-images.githubusercontent.com/35787534/197658995-51ccb5aa-f1d3-4d17-a4bb-aa54531fcd53.png)

Do you can help with problem?

**Comment by flx42** [comment]
You probably configured Slurm to allocate a subset of the cores to your job, it's not related to pyxis or enroot.

You can check which cores your job has access to with a command like this (from within the job):
```
$ grep Cpus_allowed_list /proc/self/status
```

**Comment by xinyx62** [comment]
Thanks, I have check as below. 

![image](https://user-images.githubusercontent.com/35787534/197691041-f9cdc6f6-305d-4fcf-8654-607805330e80.png)

**Comment by flx42** [comment]
Try `numactl --show` too

**Comment by xinyx62** [comment]
using numactl --show on test node, the output is :


while  enter the container,using  srun -N 1   --container-image ./hpl+test.sqsh  --pty bash

![image](https://user-images.githubusercontent.com/35787534/197694979-bff3218c-3314-41c3-853d-bae167377d2a.png)

**Comment by flx42** [comment]
Right, so it's Slurm allocating a single core to your job. You would get
the same results without using --container-image.

**Comment by inspurasc** [comment]
so how to resolved it ?

**Comment by flx42** [comment]
You have to change the Slurm configuration, but that's not related to pyxis.
