### ISSUE TITLE
pyxis plug-in components do not effective 

### ISSUE THREAD

**Issue by xinyx62** [NVIDIA/pyxis#95]
Hi 
I am install slurm on ubuntu with the command:  
./configure --prefix=/opt/slurm/22.05.5  --sysconfdir=/opt/slurm/22.05.5/etc
make -j && make install
 ldconfig -n /opt/slurm/22.05.5/lib/

Now install  pyxis with deb pakage can succeed, and 
mkdir /opt/slurm/22.05.5/etc/plugstack.conf.d
ln -s  /usr/share/pyxis/pyxis.conf /opt/slurm/22.05.5/etc/plugstack.conf.d/pyxis.conf

And the slurmd failed to restart. While run "strace -e openat srun --help >/dev/null" , the output show:

![image](https://user-images.githubusercontent.com/35787534/199943266-7da254f9-3934-4580-ad4b-a17dccccb028.png)

I have check the pyxis lib, the version is 0.14. 
![image](https://user-images.githubusercontent.com/35787534/199943405-62c58eea-6c14-4bc6-9644-b3d6c7560d8a.png)

Do you can help with problem?

**Comment by flx42** [comment]
The `incompatible Slurm plugin` message is because you need to recompile pyxis against the spank.h version of Slurm you are going to use.  This is due to a breaking change in Slurm 21.08: https://github.com/SchedMD/slurm/blob/slurm-21-08-8-2/RELEASE_NOTES#L119-L121

**Comment by rvencu** [comment]
Would you care to update the installation code with an example of how to compile correctly in this case?

**Comment by flx42** [comment]
It's not mentioned in the README: https://github.com/NVIDIA/pyxis/commit/7b96031079bd9e419f01fd0398493a0690750d98
But it's hard to give "an example of correctly" as it will depend on your build environment, but let me know if you have a suggestion for documenting that.

**Comment by rvencu** [comment]
I got the file's path; how to specify it at the make command?
`/opt/slurm/include/slurm/spank.h`

**Comment by flx42** [comment]
This should work:
```
$ CFLAGS="-I /opt/slurm/include" make
```
