### ISSUE TITLE
Fail to make container image writable

### ISSUE THREAD

**Issue by xinyx62** [NVIDIA/pyxis#97]
I have set  ENROOT_ROOTFS_WRITABLE into yes in enroot.conf. Set enroot.conf file as https://github.com/NVIDIA/pyxis/wiki/Setup#slurm-plugstack-configuration.  But I am still fail to write the container, Please help me:

![image](https://user-images.githubusercontent.com/35787534/203339355-c9ddf48a-be2c-42ec-944d-c1f436cdf00a.png)

**Comment by flx42** [comment]
Looks like you have a typo when setting the environment variable.
