### ISSUE TITLE
Fail to restart slurmd server after tweaking my PMIx configuration through systemd

### ISSUE THREAD

**Issue by inspurasc** [NVIDIA/pyxis#98]
hello,

I set pmix follow the steps as : https://github.com/NVIDIA/pyxis/wiki/Setup#slurmd-configuration
My slurmd location in /opt/slurm/20.11.9/sbin/slurmd . And I don't found /etc/default/slurmd file , so i add it m0anually. But I fail to restart the slurmd service after the seting.

**Comment by flx42** [comment]
What is the error message?

**Comment by inspurasc** [comment]
It seems the slurmd has started, but it  stopped again for some reason。 This is the slurmd.log output.

![image](https://user-images.githubusercontent.com/19197677/204965370-9f06274c-2430-4dbd-a629-deaa9528e7fd.png)

And I faild to create the /etc/default/slurmd file.  It prompted "/etc/sysconfig/slurmd" E212: Can't open file for writing". I have used  the root permission

**Comment by inspurasc** [comment]
Please provide some suggestions for above issue, thanks.

**Comment by flx42** [comment]
There are no errors visible in your log, try increasing slurmd verbosity perhaps.
