### ISSUE TITLE
Fail to srun NCG hpc-benchmarks docker 

### ISSUE THREAD

**Issue by inspurasc** [NVIDIA/pyxis#99]
I have set the .credentials file. And use NGC docker test,it seems  work : 
 srun -N 1 --cpu-bind=none --mpi=pmix  --container-image=nvcr.io#nvidia/tensorflow:18.01-py3 grep PRETTY /etc/os-release

<img width="807" alt="1670996575(1)" src="https://user-images.githubusercontent.com/19197677/207516031-189867bb-d9f7-4eaa-bcea-51a36df2810d.png">

But it fails to use on NCG  nvcr.io#nvidia/hpc-benchmarks:21.4-hpl docker . The cmd is below :
 srun --container-image=nvcr.io#nvidia/hpc-benchmarks:21.4-hpl grep PRETTY /etc/os-release
<img width="777" alt="1670996585(1)" src="https://user-images.githubusercontent.com/19197677/207516057-4f646e29-920d-4e11-a1ee-88ef8b8b1906.png">

The enroot .credentials as below:
machine nvcr.io login $oauthtoken password ...
machine authn.nvidia.com login $oauthtoken password ...

and export  ENROOT_CONFIG_PATH=/home/amax/enroot/.credentials 

So i don't know how to solve it , Please give me some suggestion, thanks.

**Comment by flx42** [comment]
It's usually a credentials problems or a network problem. Make sure it works with Docker.
Also please generate a new key, you shouldn't share it on GitHub issues.
